### ISSUE TITLE
How do you represent bencoded strings that contain a `<hex>` tag to avoid ambiguity?

### ISSUE THREAD

**Issue by josecelano** [josecelano/torrust-bencode2json#7]
Relates to: https://github.com/Chocobo1/bencode_online/issues/3

How do you represent bencoded strings that contain a <hex> tag to avoid ambiguity with the <hex> tags introduced by not utf-8 bencoded strings?

Submitted on [reddit](https://www.reddit.com/r/rust/comments/1gh3upc/comment/luui4du/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) by [Icarium-Lifestealer](https://www.reddit.com/user/Icarium-Lifestealer/)

**UPDATE**

Example, two bencoded values producing the same output:

```text
printf "13:<hex>ff</hex>" | cargo run -> "<hex>ff</hex>"  (13 bytes)
printf "1:\xff"           | cargo run -> "<hex>ff</hex>"  (1 byte)
```

List of special characters used in JSON that need to be escaped in string values:

- `\b`  Backspace (ascii code 08)
- `\f`  Form feed (ascii code 0C)
- `\n`  New line
- `\r`  Carriage return
- `\t`  Tab
- `\"`  Double quote
- `\\`  Backslash character

**Comment by josecelano** [comment]
### Proposal 1

Maybe we can always include some tags. For byte sequences containing valid UTF-8:

```json
"<utf8>spam</utf8>"
```

And not UTF-8 sequences:

```json
"<bytes>fffe</bytes>"
```

The encoded value `6:<utf8>` would be `"<utf8><utf8></utf8>"`.

**Comment by josecelano** [comment]
### Proposal 2

```json
"<string>spam</string>"
```

And not UTF-8 sequences:

```json
"<hex>fffe</hex>"
```

This would be half compatible with the other implementation.

**Comment by josecelano** [comment]
### Proposal 3

Maybe we can event simplify the metadata using just a prefix instead of a html-style tag:

```json
"string:spam"
```

And not UTF-8 sequences:

```json
"hex:fffe"
```

**Comment by josecelano** [comment]
Hey, @da2ce7, can you add an example of what we discussed today?

I mean one example like this:

```text
printf "13:<hex>ff</hex>" | cargo run -> "<hex>ff</hex>"  (13 bytes)
printf "1:\xff"           | cargo run -> "<hex>ff</hex>"  (1 byte)
```

For the problem with escaped chars you mentioned in the meeting. I can't come up with one example.

**Comment by josecelano** [comment]
> Hey, @da2ce7, can you add an example of what we discussed today?
> 
> I mean one example like this:
> 
> ```
> printf "13:<hex>ff</hex>" | cargo run -> "<hex>ff</hex>"  (13 bytes)
> printf "1:\xff"           | cargo run -> "<hex>ff</hex>"  (1 byte)
> ```
> 
> For the problem with escaped chars you mentioned in the meeting. I can't come up with one example.

Hi @da2ce7, if you have a concrete example for this ☝🏼 that would be awesome! Thanks.

**Comment by da2ce7** [comment]
The problem is that it is lossy transformation.

There are multiple bencode inputs that can produce identical json results.

The issue is if we escape XML style tags, then there is two inputs that produces the same output.

The `<\/>` input and `</>` inputs produce the same `<\/>` output.

So we don't know if the bencode input was "pre-escaped" or not.

**Comment by josecelano** [comment]
> The problem is that it is lossy transformation.
> 
> There are multiple bencode inputs that can produce identical json results.
> 
> The issue is if we escape XML style tags, then there is two inputs that produces the same output.
> 
> The `<\/>` input and `</>` inputs produce the same `<\/>` output.
> 
> So we don't know if the bencode input was "pre-escaped" or not.

Hi @da2ce7 forward slash does not need to be escaped in JSON. The two examples you mention `<\/>` and `</>` produce a different JSON value:

```text
printf "3:</>"  | cargo run -> "</>"
printf "4:<\/>" | cargo run -> "<\\/>"
```

For the backslash (hex `5C`), it's escaped but I guess we can revert it without ambiguity. We only need to undo escaped chars in the JSON value before converting them into bytes, right?

```text
printf "1:\x5c" | cargo run -> "\\"
```

**Comment by da2ce7** [comment]
I think that you are correct. If we always insert the escaping character, then it will have a reversible encoding 
. 👍

**Comment by josecelano** [comment]
> I think that you are correct. If we always insert the escaping character, then it will have a reversible encoding . 👍

Hey @da2ce7 and what proposal do you prefer? I prefer the proposal 2

> ```json
> "<string>spam</string>"
> ```

> ```json
> "<hex>ff</hex>"
> ```


Because:

- It's half-compatible with the [other implementation](https://chocobo1.github.io/bencode_online/).
- It's extensible, we can add more tags later like:

```json
"<hex>ff</hex><metada>...</medatada>"
```

as long as we include `<hex>...</hex>` at the "root" level of this kind of HTML doc.

With proposal 3, we can only add new prefixes.

**Comment by josecelano** [comment]
@da2ce7 has just told me that proposal 2 is fine.

**Comment by josecelano** [comment]
After merging this change, we have to update the [draft TEP](https://github.com/torrust/teps/pull/17).

**Comment by josecelano** [comment]
> After merging this change, we have to update the [draft TEP](https://github.com/torrust/teps/pull/17).

And also bump the version to `0.2.0` and publish it on crates.io.
